/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 projector.gltf --transform
Author: KubaJaky (https://sketchfab.com/kubakaczorxd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/film-projector-abb98f6790d44ab68ef6f670985925e6
Title: Film Projector
*/

import { useGLTF } from '@react-three/drei'

export function Projector(props) {
  const { nodes, materials } = useGLTF('../../../projector-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.22}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} position={[0, 0.61, 0]} scale={[1.07, 0.33, 1.88]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.014']} position={[-0.91, 0, 1.71]} rotation={[-Math.PI, 0, 0]} scale={[-0.13, 0.15, 0.1]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials['Material.003']} position={[0.87, -0.14, 1.72]} scale={[0.18, 0.03, 0.18]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials['Material.020']} position={[0, 1.03, -1.35]} rotation={[3.13, 0, -Math.PI]} scale={[-1, 0.03, 0.07]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials['Material.020']} position={[0, 1.03, 1.34]} rotation={[0.01, 0, 0]} scale={[1, 0.03, 0.07]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials['Material.004']} position={[-0.01, 4.16, -1.6]} rotation={[-0.2, 0, 0]} scale={[0.1, 0.75, 0.18]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials['Material.005']} position={[-0.04, 4.12, 1.39]} rotation={[0.32, 0.01, 0]} scale={[0.1, 0.75, 0.18]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials['Material.006']} position={[0.07, 5.41, -1.85]} rotation={[0, 0, Math.PI / 2]} scale={[-1, 0.27, 1]} />
          <mesh geometry={nodes.Object_20.geometry} material={materials['Material.006']} position={[0.02, 5.41, 1.84]} rotation={[2.88, 0, Math.PI / 2]} scale={[-0.86, 0.23, 0.86]} />
          <mesh geometry={nodes.Object_22.geometry} material={materials['Material.009']} position={[-0.04, 3.48, -1.1]} rotation={[Math.PI / 2, 0, 0]} scale={[0.16, 0.03, 1]} />
          <mesh geometry={nodes.Object_24.geometry} material={materials['Material.002']} position={[0.01, 3.21, -0.57]} scale={[0.99, 0.26, 0.05]} />
          <mesh geometry={nodes.Object_26.geometry} material={materials['Material.009']} position={[-0.05, 4.33, 0.17]} rotation={[-2.49, 0, -Math.PI]} scale={[-0.07, 1, 0.02]} />
          <mesh geometry={nodes.Object_28.geometry} material={materials['Material.002']} position={[0, 2.23, 2.41]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.5, 0.38, 0.5]} />
          <mesh geometry={nodes.Object_30.geometry} material={materials['Material.003']} position={[0, 2.23, 3.82]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.63, 0.43, 0.64]} />
          <mesh geometry={nodes.Object_32.geometry} material={materials['Material.003']} position={[0, 2.23, 3.72]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.58, 0.39, 0.58]} />
          <mesh geometry={nodes.Object_34.geometry} material={materials['Material.018']} position={[0, 2.23, 3.98]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.54, 0.37, 0.55]} />
          <mesh geometry={nodes.Object_36.geometry} material={materials['Material.012']} position={[-1.02, 2.3, 1.41]} rotation={[0, 0, -Math.PI / 2]} scale={[0.12, 0.04, 0.32]} />
          <mesh geometry={nodes.Object_38.geometry} material={materials['Material.012']} position={[1.02, 2.3, 1.41]} rotation={[0, 0, Math.PI / 2]} scale={[-0.12, 0.04, 0.32]} />
          <mesh geometry={nodes.Object_40.geometry} material={materials['Material.011']} position={[-1.03, 1.33, -0.63]} scale={[0.07, 0.07, 0.14]} />
          <mesh geometry={nodes.Object_42.geometry} material={materials['Material.010']} position={[-1.03, 1.33, -0.31]} scale={[0.07, 0.07, 0.14]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/projector-transformed.glb')
