/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 screen.gltf --transform
Author: Georgiy_Liahov (https://sketchfab.com/georgiyaliahov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cinema-screen-2221cf86c46f4716bf7a904c642a5542
Title: Cinema Screen
*/

import React, { useRef } from "react";
import { Decal, useGLTF, useVideoTexture } from "@react-three/drei";

export function Screen(props) {
  const screen = useRef();
  const { nodes, materials } = useGLTF("../../../screen-transformed.glb");
  const video = useVideoTexture("../../../front-end.mp4");
  return (
    <group {...props} dispose={null} scale={[0.5, 0.4, 0.4]}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.black} />
      <mesh
        ref={screen}
        geometry={nodes.Object_5.geometry}
        material={materials.wite}
      >
        <Decal
          mesh={screen}
          position={[0, 5.5, 0]}
          rotation={[0, 0, 0]}
          scale={[14.6, 7.5, 7.5]}
        >
          <meshBasicMaterial map={video} />
        </Decal>
      </mesh>
    </group>
  );
}

useGLTF.preload("/screen-transformed.glb");
