/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 desk.glb --transform
Author: djones_CQU (https://sketchfab.com/djones_CQU)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-night-owls-desk-1645fa150e5243b29fc9394312c348c3
Title: The Night Owl's Desk
*/

import { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Desk(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/desk-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" position={[0.11, 0.23, -2.31]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="45b254b5d2ae41faa5304c013dfba576fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="calculator" position={[14.69, -0.29, 23.3]} rotation={[0, 0.56, 0]} scale={[1.35, 0.57, 1.31]}>
                  <mesh name="calculator_buttons_calc_0" geometry={nodes.calculator_buttons_calc_0.geometry} material={materials.buttons_calc} />
                  <mesh name="calculator_base_calc_0" geometry={nodes.calculator_base_calc_0.geometry} material={materials.base_calc} />
                  <mesh name="calculator_display_calc_0" geometry={nodes.calculator_display_calc_0.geometry} material={materials.display_calc} />
                </group>
                <group name="computer" position={[-16.1, 0.3, -0.61]} scale={1.91}>
                  <mesh name="computer_gold_cpu_0" geometry={nodes.computer_gold_cpu_0.geometry} material={materials.buttons_calc} />
                  <mesh name="computer_base_cpu_0" geometry={nodes.computer_base_cpu_0.geometry} material={materials.base_cpu} />
                  <mesh name="computer_screen_cpu_0" geometry={nodes.computer_screen_cpu_0.geometry} material={materials.screen_cpu} />
                </group>
                <group name="lamp" position={[-12.29, 1.11, 33.01]} rotation={[0, 0.63, 0]} scale={1.38}>
                  <mesh name="lamp_gold_lamp_0" geometry={nodes.lamp_gold_lamp_0.geometry} material={materials.gold_lamp} />
                  <mesh name="lamp_dark_0" geometry={nodes.lamp_dark_0.geometry} material={materials.dark} />
                  <mesh name="lamp_metal_lamp_0" geometry={nodes.lamp_metal_lamp_0.geometry} material={materials.metal_lamp} />
                  <mesh name="lamp_bulb_lamp_0" geometry={nodes.lamp_bulb_lamp_0.geometry} material={materials.bulb_lamp} />
                </group>
                <group name="pSphere3" position={[15.64, 0.5, 3.72]} rotation={[-1.68, 0.48, 0.24]}>
                  <mesh name="pSphere3_standardSurface4_0" geometry={nodes.pSphere3_standardSurface4_0.geometry} material={materials.standardSurface4} />
                  <mesh name="pSphere3_chrome1_0" geometry={nodes.pSphere3_chrome1_0.geometry} material={materials.chrome1} />
                  <mesh name="pSphere3_pasted__chrome1_0" geometry={nodes.pSphere3_pasted__chrome1_0.geometry} material={materials.pasted__chrome1} />
                </group>
                <group name="pCylinder5" position={[7.46, -0.12, -29.27]} rotation={[0, -1.26, 0]} scale={2}>
                  <mesh name="pCylinder5_base_mug_0" geometry={nodes.pCylinder5_base_mug_0.geometry} material={materials.base_mug} />
                  <mesh name="pCylinder5_Default_Material_0" geometry={nodes.pCylinder5_Default_Material_0.geometry} material={materials.pasted__chrome1} />
                  <mesh name="pCylinder5_fluid_mug_0" geometry={nodes.pCylinder5_fluid_mug_0.geometry} material={materials.fluid_mug} />
                  <mesh name="pCylinder5_coaster_mug_0" geometry={nodes.pCylinder5_coaster_mug_0.geometry} material={materials.coaster_mug} />
                </group>
                <group name="pCube4" position={[-15.35, 0.57, -35.2]} rotation={[0, 1.05, 0]} scale={1.65}>
                  <mesh name="pCube4_ball_rose3_0" geometry={nodes.pCube4_ball_rose3_0.geometry} material={materials.ball_rose3} />
                  <mesh name="pCube4_ball_pink1_0" geometry={nodes.pCube4_ball_pink1_0.geometry} material={materials.ball_pink1} />
                  <mesh name="pCube4_metal4_0" geometry={nodes.pCube4_metal4_0.geometry} material={materials.metal4} />
                  <mesh name="pCube4_ball_purple1_0" geometry={nodes.pCube4_ball_purple1_0.geometry} material={materials.ball_purple1} />
                  <mesh name="pCube4_ball_violet1_0" geometry={nodes.pCube4_ball_violet1_0.geometry} material={materials.ball_violet1} />
                  <mesh name="pCube4_ball_blue3_0" geometry={nodes.pCube4_ball_blue3_0.geometry} material={materials.ball_blue3} />
                  <mesh name="pCube4_base_0" geometry={nodes.pCube4_base_0.geometry} material={materials.base} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/desk-transformed.glb')
